- name: "blocked"
  description: "This is blocked"
  color: "e92f1d"

- name: "bug"
  description: "Something isn't working"
  color: "d73a4a"

- name: "chore"
  description: "Changes that don't affect the codebase (eg. CI, docs)"
  color: "eba8cc"

- name: "ci"
  description: "Changes to our CI configuration files and scripts"
  color: "721cdb"

- name: "dependencies"
  description: "Update of dependencies"
  color: "6f38c2"

- name: "documentation"
  description: "Improvements or additions to documentation"
  color: "0075ca"

- name: "duplicate"
  description: "This issue or pull request already exists"
  color: "cfd3d7"

- name: "enhancement"
  description: "New feature or request"
  color: "a2eeef"

- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "invalid"
  description: "This doesn't seem right"
  color: "e4e669"

- name: "command:build"
  description: "Related to build command"
  color: "aaa3dc"

- name: "command:dev"
  description: "Related to dev command"
  color: "aaa3dc"

- name: "command:generate"
  description: "Related to generate command"
  color: "aaa3dc"

- name: "command:help"
  description: "Related to help command"
  color: "aaa3dc"

- name: "command:install"
  description: "Related to install command"
  color: "aaa3dc"

- name: "command:login"
  description: "Related to login command"
  color: "aaa3dc"

- name: "command:logout"
  description: "Related to logout command"
  color: "aaa3dc"

- name: "command:new"
  description: "Related to new command"
  color: "aaa3dc"

- name: "command:publish"
  description: "Related to publish command"
  color: "aaa3dc"

- name: "command:start"
  description: "Related to start command"
  color: "aaa3dc"

- name: "command:unpublish"
  description: "Related to unpublish command"
  color: "aaa3dc"

- name: "question"
  description: "Further information is requested"
  color: "d876e3"

- name: "refactor"
  description: "Code change that neither fixes a bug nor adds a feature"
  color: "a3f2e8"

- name: "tests"
  description: "Adding missing tests or correcting existing tests"
  color: "7f8f92"

- name: "wontfix"
  description: "This will not be worked on"
  color: "ffffff"
