command:build:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/build.command.ts
          - src/action/actions/build.action.ts

command:dev:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/dev.command.ts
          - src/action/actions/dev.action.ts

command:generate:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/generate.command.ts
          - src/action/actions/generate.action.ts

command:install:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/install.command.ts
          - src/action/actions/install.action.ts

command:login:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/login.command.ts
          - src/action/actions/login.action.ts

command:logout:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/logout.command.ts
          - src/action/actions/logout.action.ts

command:new:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/new.command.ts
          - src/action/actions/new.action.ts

command:publish:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/publish.command.ts
          - src/action/actions/publish.action.ts

command:start:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/start.command.ts
          - src/action/actions/start.action.ts

command:unpublish:
  - changed-files:
      - any-glob-to-any-file:
          - src/command/commands/unpublish.command.ts
          - src/action/actions/unpublish.action.ts

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*
          - docs/**/*
