import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const CONFIG_IMPORT = 'import { defineConfig } from "nanoforge/config";\n';
const DEFINE_CONFIG_CALL = /defineConfig\(([\s\S]*)\);/;

/**
 * Configs generated by `nf new` import `defineConfig` from `nanoforge/config`, which is not
 * published yet, so the CLI cannot load them in a project scaffolded with `--skip-install`.
 * `defineConfig` is an identity function: stripping the import and the call keeps the exact
 * generated config while making it loadable without dependencies.
 *
 * TODO: remove once `nanoforge` is published with its `./config` export.
 */
export const stripDefineConfig = (projectDir: string): void => {
  const path = ["nanoforge.config.ts", "nanoforge.config.js"]
    .map((file) => join(projectDir, file))
    .find((file) => existsSync(file));
  if (!path) throw new Error(`No nanoforge config found in '${projectDir}'`);

  const content = readFileSync(path, "utf-8");
  if (!content.includes(CONFIG_IMPORT) || !DEFINE_CONFIG_CALL.test(content))
    throw new Error(`Unexpected config format in '${path}', update stripDefineConfig`);

  writeFileSync(path, content.replace(CONFIG_IMPORT, "").replace(DEFINE_CONFIG_CALL, "$1;"));
};

/**
 * Engine packages imported by the generated entry file are not published yet, so builds run
 * against an entry file without any dependency.
 *
 * TODO: remove once the engine v2 packages are published.
 */
export const writeStandaloneEntry = (projectDir: string, entry = "src/main.ts"): void => {
  writeFileSync(join(projectDir, entry), 'console.log("nanoforge");\n');
};
