name: synchronize-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli
        uses: actions/checkout@v5
        with:
          path: cli

      - name: Checkout docs
        uses: actions/checkout@v5
        with:
          path: docs
          repository: nanoforge-dev/docs
          token: ${{ secrets.ACTIONS_KEY }}

      - name: setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "username@users.noreply.github.com"

      - name: synchronize docs
        run: |
          mkdir -p docs/cli
          cp cli/docs/. -r docs/cli
          cd docs
          git add .
          git commit -m "chore(cli): updating docs"
          git push origin main
