name: Synchronize Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "docs.json"
  workflow_dispatch:

env:
  SOURCE_PATH: cli

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli
        uses: actions/checkout@v6
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: pnpm install
        uses: ./cli/.github/actions/pnpm-install
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: synchronize docs
        uses: ./cli/node_modules/@nanoforge-dev/actions/src/synchronize-docs
        with:
          source-docs: ${{ env.SOURCE_PATH }}/docs
          destination-docs: docs/schematics
          repository: nanoforge-dev/docs
          config: ${{ env.SOURCE_PATH }}/docs.json
          token: ${{ secrets.ACTIONS_KEY }}
          commit-message: "chore(cli): synchronize docs"
